<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: input.proto

namespace Carno\Validator\Tests\Samples\Input;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>carno.validator.tests.samples.input.RequestA</code>
 */
class RequestA extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    private $id = 0;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>.carno.validator.tests.samples.input.SubRequestA sub = 5;</code>
     */
    private $sub = null;
    /**
     * Generated from protobuf field <code>repeated string chars = 8;</code>
     */
    private $chars;
    /**
     * Generated from protobuf field <code>repeated .carno.validator.tests.samples.input.RField fields = 9;</code>
     */
    private $fields;

    public function __construct() {
        \GPBMetadata\Input::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.carno.validator.tests.samples.input.SubRequestA sub = 5;</code>
     * @return \Carno\Validator\Tests\Samples\Input\SubRequestA
     */
    public function getSub()
    {
        return $this->sub;
    }

    /**
     * Generated from protobuf field <code>.carno.validator.tests.samples.input.SubRequestA sub = 5;</code>
     * @param \Carno\Validator\Tests\Samples\Input\SubRequestA $var
     * @return $this
     */
    public function setSub($var)
    {
        GPBUtil::checkMessage($var, \Carno\Validator\Tests\Samples\Input\SubRequestA::class);
        $this->sub = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string chars = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getChars()
    {
        return $this->chars;
    }

    /**
     * Generated from protobuf field <code>repeated string chars = 8;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setChars($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->chars = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .carno.validator.tests.samples.input.RField fields = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFields()
    {
        return $this->fields;
    }

    /**
     * Generated from protobuf field <code>repeated .carno.validator.tests.samples.input.RField fields = 9;</code>
     * @param \Carno\Validator\Tests\Samples\Input\RField[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFields($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Carno\Validator\Tests\Samples\Input\RField::class);
        $this->fields = $arr;

        return $this;
    }

}

