<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: input.proto

namespace Carno\Validator\Tests\Samples\Input;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>carno.validator.tests.samples.input.RField</code>
 */
class RField extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    private $id = 0;
    /**
     * Generated from protobuf field <code>int32 kid = 2;</code>
     */
    private $kid = 0;
    /**
     * Generated from protobuf field <code>string desc = 3;</code>
     */
    private $desc = '';

    public function __construct() {
        \GPBMetadata\Input::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 kid = 2;</code>
     * @return int
     */
    public function getKid()
    {
        return $this->kid;
    }

    /**
     * Generated from protobuf field <code>int32 kid = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setKid($var)
    {
        GPBUtil::checkInt32($var);
        $this->kid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string desc = 3;</code>
     * @return string
     */
    public function getDesc()
    {
        return $this->desc;
    }

    /**
     * Generated from protobuf field <code>string desc = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDesc($var)
    {
        GPBUtil::checkString($var, True);
        $this->desc = $var;

        return $this;
    }

}

