<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: input.proto

namespace Carno\Validator\Tests\Samples\Input;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>carno.validator.tests.samples.input.SubRequestA</code>
 */
class SubRequestA extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 sid = 1;</code>
     */
    private $sid = 0;
    /**
     * Generated from protobuf field <code>string title = 2;</code>
     */
    private $title = '';

    public function __construct() {
        \GPBMetadata\Input::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 sid = 1;</code>
     * @return int
     */
    public function getSid()
    {
        return $this->sid;
    }

    /**
     * Generated from protobuf field <code>int32 sid = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSid($var)
    {
        GPBUtil::checkInt32($var);
        $this->sid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string title = 2;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

}

