<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: input.proto

namespace GPBMetadata;

class Input
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac8020a0b696e7075742e70726f746f12236361726e6f2e76616c696461" .
            "746f722e74657374732e73616d706c65732e696e70757422af010a085265" .
            "717565737441120a0a026964180120012805120c0a046e616d6518022001" .
            "2809123d0a0373756218052001280b32302e6361726e6f2e76616c696461" .
            "746f722e74657374732e73616d706c65732e696e7075742e537562526571" .
            "7565737441120d0a056368617273180820032809123b0a066669656c6473" .
            "18092003280b322b2e6361726e6f2e76616c696461746f722e7465737473" .
            "2e73616d706c65732e696e7075742e524669656c6422290a0b5375625265" .
            "717565737441120b0a03736964180120012805120d0a057469746c651802" .
            "20012809222f0a06524669656c64120a0a026964180120012805120b0a03" .
            "6b6964180220012805120c0a0464657363180320012809620670726f746f" .
            "33"
        ));

        static::$is_initialized = true;
    }
}

